contributions/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from contributions import views

urlpatterns = patterns('',
    url(r'^$', views.MultiContributionView.as_view(), name="post_list"),
    url(r'^(?P<title>[0-9A-Za-z]+)-(?P<pk>\d+)/$', views.SingleContributionView.as_view(), name='detail'),
    url(r'^add/$', login_required(views.AddContributionView.as_view()), name='post'),
    url(r'^edit/(?P<title>[0-9A-Za-z]+)-(?P<pk>\d+)/$', login_required(views.EditContributionView.as_view()), name='edit'),
    url(r'^save_new/$', login_required(views.SaveNewPostForm.as_view()), name='saveNewPost'),
    url(r'^save_existing/$', login_required(views.SaveExistingPostForm.as_view()), name='saveExistingPost'),
    url(r'^comment/save/$', login_required(views.CommentPost), name='comment_save'),
    url(r'^comment/remove/$', login_required(views.CommentRemove), name='comment_remove'),
)

lxp/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from userProfile import views
from siteInfo import views
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('contributions.urls', namespace="feed")),
    url(r'^contributions/', include('contributions.urls', namespace="contributions")),
    url(r'^about/', views.AboutView.as_view(), name='about'),
    url(r'^accounts/', include('accounts.urls',namespace="accounts")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^career/', include('careers.urls',namespace="careers")),
    url(r'^community/', views.CommunityView.as_view(), name='community'),
    url(r'^contact/', views.ContactView.as_view(), name='contact'),
    url(r'^legal/', views.LegalView.as_view(), name='legal'),
    url(r'^tags/', include('tags.urls',namespace="tags")),
    url(r'^story/', include('userProfile.urls',namespace="myUserProfile")),
    url(r'^search/', include('search.urls',namespace="search")),
    
    #url(r'^info/', include('about.urls',namespace="siteInfo")),
    
    
    url(r'^(?P<tag>[0-9A-Za-z]+)-(?P<pk>[0-9]+)/', include('tags.urls',namespace="tagDetail")),
    url(r'^(?P<handle>[0-9A-Za-z]+)_(?P<pk>[0-9]+)/', include('userProfile.urls',namespace="userProfile")),
    
)

tags/urls.py
from django.conf.urls import patterns, url
from tags import views

urlpatterns = patterns('',
    url(r'^$', views.TagsView.as_view(), name='tagView'),
    url(r'^search/$', views.Search.as_view(), name='search'),
    url(r'^save/$', views.SaveTag, name='saveTag'),
    url(r'^remove/$', views.RemoveTag, name='removeTag'),
)

userProfile/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from userProfile import views

urlpatterns = patterns('',
    url(r'^$', views.Story.as_view(), name="story"),
    url(r'^edit/$', login_required(views.EditStory.as_view()), name="edit"),
    url(r'^edit/save/$', login_required(views.Update.as_view()), name="saveEdit"),
    url(r'^edit/image/$', login_required(views.ImageUpload.as_view()), name="uploadImage"),
    url(r'^view/$', login_required(views.Story.as_view()), name="mystory"),
)

userProfile/models.py
# Summary: Models for user Profiles, user Points and uploading Documents(for now this is profile pics only).
from django.db import models
from django.contrib.auth.models import User
from tags.models import Tags
import re

class Document(models.Model):
    file = models.FileField(upload_to='documents/%Y/%m/%d')
    
class Profile(models.Model):
    gender = models.CharField(max_length=50,blank=True)
    type = models.CharField(max_length=100, blank=True)
    hash_id = models.CharField(max_length=200,blank=True)
    fname = models.CharField(max_length=30,blank=True)
    lname = models.CharField(max_length=30,blank=True)
    handle = models.CharField(max_length=30,blank=True)
    dateJoined = models.DateTimeField(blank=True)
    company = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=30, blank=True)
    city = models.CharField(max_length=30, blank=True)
    state = models.CharField(max_length=20, blank=True)
    title = models.CharField(max_length=150, blank=True)
    industry = models.CharField(max_length=150, blank=True)
    about = models.CharField(max_length=2000, blank=True)
    pic = models.CharField(max_length=400, blank=True, default="default.png")
    dateJoined = models.DateTimeField(blank=True,null=True)
    linkedin_token = models.CharField(max_length=400, blank=True)
    linkedin_created = models.DateTimeField(blank=True,null=True)
    pass
    
    def __unicode__(self):
         return self.handle
         
    def clean_handle(self, handle):
        handle = re.sub(r'\W',"",handle)
        handle = handle.replace("_",'')
        handle = handle.strip()
        
        return handle
    
class Points(models.Model):
    user = models.OneToOneField(Profile,parent_link=True)
    total = models.IntegerField(blank=True, default=0)
    post_pts = models.IntegerField(blank=True, default=0)
    comment_pts = models.IntegerField(blank=True, default=0)
    vote_pts = models.IntegerField(blank=True, default=0)
    
    def __unicode__(self):
         return self.total

userProfile/forms.py
# Summary: DocumentForm handles the upload of user files(for now this is intended for only a user's profile picture).
from django import forms

class DocumentForm(forms.Form):
    file = forms.FileField()

userProfile/views.py
# Summary: View user's stories(profile), edit your own story(profile) and upload a profile picture to AWS S3.
import random
import os
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from userProfile.forms import DocumentForm
from userProfile.models import Document, Profile, Points
from handleImageUpload import image_upload
from contributions.models import Posts

class Story(generic.DetailView):
    template_name = 'userProfile/story.html'
    context_object_name = 'profile'
    
    def get_object(self, **kwargs):
        # Determine if the user is accessing their own profile or another user's profile.
        if "pk" not in self.kwargs:
            self.user_id = self.request.user.id
            self.my_profile = True
            return get_object_or_404(Profile, pk=self.request.user.id) 
        else:
            self.user_id = self.kwargs["pk"]
            self.my_profile = False
            return get_object_or_404(Profile, pk=self.kwargs["pk"]) 
        
    def get_context_data(self, **kwargs):
        context = super(Story, self).get_context_data(**kwargs)
        user_id = self.user_id
        context["myProfile"] = self.my_profile     
        context["points"] = Points.objects.get(user_id = self.user_id)
        context["posts"] = Posts.objects.filter(user_id = self.user_id).prefetch_related('tags')
        # Determine if the request is coming from an authenticated user or a guest.
        if self.request.user.is_authenticated():
            context["authenticated"] = True
        else:
            context["authenticated"] = False
        return context
  
class EditStory(generic.DetailView):
    template_name = 'userProfile/edit.html'
    context_object_name = 'profile'
    
    def get_object(self):
        return get_object_or_404(Profile, pk=self.request.user.id)
    
    def get_context_data(self, **kwargs):
        context = super(EditStory, self).get_context_data(**kwargs)
        context["user"] = self.request.user
        return context

class ImageUpload(generic.FormView):
    form_class = DocumentForm
    
    def form_invalid(self, form):
        return HttpResponseRedirect(reverse('myUserProfile:edit')) 

    def form_valid(self, form):
        if self.request.method == 'POST':
            # Upload the file using the Document form.
            # Image is temporarily saved to the '/temp' directory in this project.
            newdoc = Document(file = self.request.FILES['file'])
            newdoc.save()
            
            # Create a FileName for AWS S3
            temp_file_name = str(newdoc.file)
            file_extension = os.path.splitext(temp_file_name)[1]
            userFirst_name = self.request.user.first_name
            userLast_name = self.request.user.last_name
            user_id = self.request.user.id
            s3_file_name = str(userFirst_name)+"_"+str(userLast_name)+"_"+str(user_id)+"_"+str(random.randint(1,200))+str(random.randint(1,300))+str(file_extension.lower())
            
            # Upload the File to S3 and Save the New File Name to User's Profile.
            image_upload(temp_file_name, s3_file_name, user_id)
            
            return HttpResponseRedirect(reverse('myUserProfile:edit'))
        else:
            # Upload request must be made via POST.
            return HttpResponseRedirect(reverse('myUserProfile:edit'))
            
class Update(generic.View):  
    def post(self, request, *args, **kwargs):
        value = self.request.POST["updateValue"]
        target = self.request.POST["target"]
        user_id = self.request.user.id;
        user = User.objects.get(pk=user_id)
        profile = Profile.objects.get(pk=user_id)
        
        if target == "fname":
            if value != profile.fname:
                profile.fname = value
                profile.save(update_fields=['fname'])
                user.first_name = value
                user.save(update_fields=['first_name'])
                return HttpResponse("Successly Updated Your First Name to " + str(value) + ".")
            else:
                return HttpResponse(400)

        elif target == "lname":
            if value != profile.lname:
                profile.lname = value
                profile.save(update_fields=['lname'])
                user.last_name = value
                user.save(update_fields=['last_name'])
                return HttpResponse("Successly Updated Your Last Name to " + str(value) + ".")
            else:
                return HttpResponse(400)
        
        elif target == "company":
            if value != profile.company:
                profile.company = value
                profile.save(update_fields=['company'])
                return HttpResponse("Successly Updated Your Company to " + str(value) + ".")
            else:
                return HttpResponse(400)
        
        elif target == "title":
            if value != profile.title:
                profile.title = value
                profile.save(update_fields=['title'])
                return HttpResponse("Successly Updated Your Title to " + str(value) + ".")
            else:
                return HttpResponse(400)
            
        elif target == "city":
            if value != profile.city:
                profile.city = value
                profile.save(update_fields=['city'])
                return HttpResponse("Successly Updated Your City to " + str(value) + ".")
            else:
                return HttpResponse(400)
            
        elif target == "state":
            if value != profile.state:
                profile.state = value
                profile.save(update_fields=['state'])
                return HttpResponse("Successly Updated Your State to " + str(value) + ".")
            else:
                return HttpResponse(400)
            
        elif target == "email":
            if value != user.email:
                user.email = value
                user.username = value
                user.save(update_fields=['username','email'])
                return HttpResponse("Successly Updated Your Email Login to " + str(value) + ".")
            else:
                return HttpResponse(400)
            
    def get(self, request, *args, **kwargs):
        return HttpResponse("Error")

userProfile/templates/userProfile/edit.html
{% extends "core/base.html" %}
{% load url from future %}
{% load staticfiles %}

{% block content %}

{% include "core/topNav_detail_in.html" %}
<script type="text/javascript"> 
	var page = "editStory"
</script>

<div class="content">
	<div class="content-inner">
		<div class="table">
			<h3 class="table-title">Edit Story Details</h3>
			<div class="table-row" >
				<div class="table-col1" style="border-top:2px solid #ddd;height:219px;">
					<label for="fname" >Story Photo</label>
				</div>
				<div class="table-col2" style="border-top:2px solid #ddd;">
					<div class="image-preview">
						<img src="https://d3op517cq3iurb.cloudfront.net/{{profile.pic}}" name="pic" id="pic"/>
					</div>
					<form method="POST" action="{% url 'myUserProfile:uploadImage' %}" enctype="multipart/form-data">
						<input type="file" name="file" id="file" />
						<input type="submit" class="upload-button seagreen-button-flat" value="Upload Photo" />
						{% csrf_token %}
					</form>
				</div>
			</div>
			<div class="table-row" >
				<div class="table-col1">
					<label for="fname" >First Name</label>
				</div>
				<div class="table-col2">
					<form id="fname_form" method="POST" action="{% url 'myUserProfile:saveEdit' %}">
						<input type="text" name="updateValue" id="fname" value="{{ profile.fname }}" placeholder="First Name"/>
						<input type="hidden" name="target" value="fname" />
						{% csrf_token %}
					</form>
				</div>
			</div>
			<div class="table-row">
				<div class="table-col1">
					<label for="lname" >Last Name</label>
				</div>
				<div class="table-col2">
					<form id="lname_form" method="POST" action="{% url 'myUserProfile:saveEdit' %}">
						<input type="text" name="updateValue" id="lname" value="{{ profile.lname }}" placeholder="Last Name"/>
						<input type="hidden" name="target" value="lname" />
						{% csrf_token %}
					</form>
				</div>
			</div>
			<div class="table-row">
				<div class="table-col1">
					<label for="company" >Company</label>
				</div>
				<div class="table-col2">
					<form id="company_form" method="POST" action="{% url 'myUserProfile:saveEdit' %}">
						<input type="text" name="updateValue" id="company" value="{{ profile.company }}" placeholder="Company"/>
						<input type="hidden" name="target" value="company" />
						{% csrf_token %}
					</form>
				</div>
			</div>
			<div class="table-row">
				<div class="table-col1">
					<label for="title" >Title</label>
				</div>
				<div class="table-col2">
					<form id="title_form" method="POST" action="{% url 'myUserProfile:saveEdit' %}">
						<input type="text" name="updateValue" id="title" value="{{ profile.title }}" placeholder="Title"/>
						<input type="hidden" name="target" value="title" />
						{% csrf_token %}
					</form>
				</div>
			</div>
			<div class="table-row">
				<div class="table-col1">
					<label for="city" >City</label>
				</div>
				<div class="table-col2">
					<form id="city_form" method="POST" action="{% url 'myUserProfile:saveEdit' %}">
						<input type="text" name="updateValue" id="city" value="{{ profile.city }}" placeholder="City"/>
						<input type="hidden" name="target" value="city" />
						{% csrf_token %}
					</form>
				</div>
			</div>
			<div class="table-row">
				<div class="table-col1">
					<label for="state">State</label>
				</div>
				<div class="table-col2">
					<form id="state_form" method="POST" action="{% url 'myUserProfile:saveEdit' %}">
						<input type="text" name="updateValue" id="state" value="{{ profile.state }}" placeholder="State"/>
						<input type="hidden" name="target" value="state" />
						{% csrf_token %}
					</form>
				</div>
			</div>
			<div class="table-row">
				<div class="table-col1">
					<label for="email">Email</label>
				</div>
				<div class="table-col2">
					<form id="email_form" method="POST" action="{% url 'myUserProfile:saveEdit' %}">
						<input type="text" name="updateValue" id="email" value="{{ user.email }}" placeholder="Email Address (Used for Login)"/>
						<input type="hidden" name="target" value="email" />
						{% csrf_token %}
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

userProfile/templates/userProfile/story.html
{% extends "core/base.html" %}
{% load url from future %}
{% load staticfiles %}

{% block content %}
{% if authenticated == False %}
	{% include "core/topNav_detail_out.html" %}
{% else %}
	{% include "core/topNav_detail_in.html" %}
{% endif %}
<script type="text/javascript"> 
	{% if myProfile == False %}
		var page = "story";
		var story_url = "{{ profile.fname }}-{{ profile.lname }}-{{ profile.id }}";
	{% else %}
		var page = "myStory";
	{% endif %}
	//var story_url = "{{ profile.fname }}/{{ profile.lname }}";
	$(document).ready(function(){
		$(".limited-text").dotdotdot({height:65});
	
	})
</script>

<div class="content">
	<div class="content-inner">
		<div class="story">
			<div class="story-left" id="left-story">
				<div class="img">
					<div>
						<img src="https://d3op517cq3iurb.cloudfront.net/{{profile.pic}}" />
					</div>
				</div>
				<h1>{{ profile.fname }} {{ profile.lname }}</h1>
				<p>{{ profile.title }}</p>
				<div class="details">
					<div>
						<span>XP</span>
						<p>{{ points.total }}</p>
					</div>
					{% if profile.city and profile.state %}
					<div>
						<span><i class="icon-map-marker"></i></span>
						<p>{{ profile.city }}, {{ profile.state }}</p>
					</div>
					{% endif %}
					{% if profile.company %}
					<div>
						<span><i class="icon-briefcase"></i></span>
						<p>{{ profile.company }}</p>
					</div>
					{% endif %}
					<div>
						<span><i class="icon-time"></i></span>
						<p><span class="muted">Joined on</span> {{ profile.dateJoined|date:"M d, Y" }}</p>
					</div>
				</div>
			</div>
			<div class="story-right">
				<h3>Experiences Lended</h3>
				<div class="tab-content">
					{% if posts %}
					<ul id="contributionHolder" class="right-ul">
						{% for post in posts %}
						<li class="content-item" id="post_{{post.id}}">
							<h1 class="volk-font">
								{% if myProfile == True %}
									<a href="{% url 'contributions:detail' post.url post.id %}" style="float:left;width:85%;">{{post.title}}</a>
									<a class="edit" href="{% url 'contributions:edit' post.url post.id %}" style="float:right">Edit <i class="icon-edit"></i></a></h1>
								{% else %}
									<a href="{% url 'contributions:detail' post.url post.id %}" >{{post.title}}</a>
								{% endif %}
							</h1>
							<p class="volk-font limited-text">{{ post.description }}</p>
							<div class="tag-holder">
								{% for tag in post.tags.all %}
								<a class="tag volk-font grey-button-flat" href="{% url 'tagDetail:tagView' tag.handle tag.id %}">{{tag.name}} </a>
								{% endfor %}
							</div>
						</li>
						
						{% endfor %}
					</ul>
					{% else %}
					<div class="alert"> <button type="button" class="close" data-dismiss="alert">×</button>{{ profile.fname }} has not Contributed any Experiences.</div>
					{% endif %}
				</div>
				{% if is_paginated %}
						<div class="pagination">
				            <span class="page-links">
				                {% if page_obj.has_previous %}
				                    <a href="?page={{ page_obj.previous_page_number }}"><<</a>
				                {% endif %}
				                <span class="page-current">
				                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
				                </span>
				                {% if page_obj.has_next %}
				                    <a href="?page={{ page_obj.next_page_number }}">>></a>
				                {% endif %}
				            </span>
				        </div>
				{% endif %}
			</div>
		</div>
		
	</div>
</div>
{% endblock %}