accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
    url(r'^login/', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout/', 'django.contrib.auth.views.logout',{'next_page': '/accounts/login/'}, name="logout"),
    url(r'^signup/$', views.SignUp.as_view(), name="signup"),
    url(r'^signup/success/$', views.signupSuccess, name="signup_success"),
    url(r'^signup/error/$', views.signupError, name="signup_error"),
    url(r'^user/password/reset/$','django.contrib.auth.views.password_reset', {'post_reset_redirect' : 'done'}, name="password_reset"),
    url(r'^user/password/reset/done/$','django.contrib.auth.views.password_reset_done', name="reset_done"),
    url(r'^user/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/accounts/user/password/done/'}),
    url(r'^user/password/done/$', 'django.contrib.auth.views.password_reset_complete'),
)

careers/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from careers import views

urlpatterns = patterns('',
    url(r'^categorize$', login_required(views.Categorize.as_view()), name="categorize"),
    url(r'^(?P<careerCategory>[0-9A-Za-z]+)$', views.Career.as_view(), name="career")
)

contributions/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from contributions import views

urlpatterns = patterns('',
    url(r'^$', views.MultiContributionView.as_view(), name="post_list"),
    url(r'^(?P<title>[0-9A-Za-z]+)-(?P<pk>\d+)/$', views.SingleContributionView.as_view(), name='detail'),
    url(r'^add/$', login_required(views.AddContributionView.as_view()), name='post'),
    url(r'^edit/(?P<title>[0-9A-Za-z]+)-(?P<pk>\d+)/$', login_required(views.EditContributionView.as_view()), name='edit'),
    url(r'^save_new/$', login_required(views.SaveNewPostForm.as_view()), name='saveNewPost'),
    url(r'^save_existing/$', login_required(views.SaveExistingPostForm.as_view()), name='saveExistingPost'),
    url(r'^comment/save/$', login_required(views.CommentPost), name='comment_save'),
    url(r'^comment/remove/$', login_required(views.CommentRemove), name='comment_remove'),
)

lxp/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from userProfile import views
from siteInfo import views
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('contributions.urls', namespace="feed")),
    url(r'^contributions/', include('contributions.urls', namespace="contributions")),
    url(r'^about/', views.AboutView.as_view(), name='about'),
    url(r'^accounts/', include('accounts.urls',namespace="accounts")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^career/', include('careers.urls',namespace="careers")),
    url(r'^community/', views.CommunityView.as_view(), name='community'),
    url(r'^contact/', views.ContactView.as_view(), name='contact'),
    url(r'^legal/', views.LegalView.as_view(), name='legal'),
    url(r'^tags/', include('tags.urls',namespace="tags")),
    url(r'^story/', include('userProfile.urls',namespace="myUserProfile")),
    url(r'^search/', include('search.urls',namespace="search")),
    
    #url(r'^info/', include('about.urls',namespace="siteInfo")),
    
    
    url(r'^(?P<tag>[0-9A-Za-z]+)-(?P<pk>[0-9]+)/', include('tags.urls',namespace="tagDetail")),
    url(r'^(?P<handle>[0-9A-Za-z]+)_(?P<pk>[0-9]+)/', include('userProfile.urls',namespace="userProfile")),
    
)

tags/urls.py
from django.conf.urls import patterns, url
from tags import views

urlpatterns = patterns('',
    url(r'^$', views.TagsView.as_view(), name='tagView'),
    url(r'^search/$', views.Search.as_view(), name='search'),
    url(r'^save/$', views.SaveTag, name='saveTag'),
    url(r'^remove/$', views.RemoveTag, name='removeTag'),
)

userProfile/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from userProfile import views

urlpatterns = patterns('',
    url(r'^$', views.Story.as_view(), name="story"),
    url(r'^edit/$', login_required(views.EditStory.as_view()), name="edit"),
    url(r'^edit/save/$', login_required(views.Update.as_view()), name="saveEdit"),
    url(r'^edit/image/$', login_required(views.ImageUpload.as_view()), name="uploadImage"),
    url(r'^view/$', login_required(views.Story.as_view()), name="mystory"),
)

contributions/models.py
# Summary: Models for contributions(aka Posts) and contributions' comments(aka Comments).
import re
from django.db import models
from django.contrib.auth.models import User
from userProfile.models import Profile
from tags.models import Tags

class Comments(models.Model):
    contribution_id = models.IntegerField()
    user = models.OneToOneField(Profile,parent_link=True)
    text = models.CharField(max_length=1500,blank=True)
    date_created = models.IntegerField(max_length=20)
    remove = models.IntegerField(max_length=1,default=0)
    pass
    
    def __unicode__(self):
         return self.profile.fname
    
    class Meta:
        ordering = ('-date_created',)
    
class Posts(models.Model):
    type = models.CharField(max_length=20,blank=True)
    uid_old = models.CharField(max_length=150,blank=True)
    user = models.OneToOneField(Profile,parent_link=True)
    title = models.CharField(max_length=300)
    url = models.CharField(max_length=300,blank=True)
    description = models.CharField(max_length=12000)
    formatted_description = models.CharField(max_length=20000,blank=True)
    date_created = models.IntegerField(max_length=20,blank=True)
    remove = models.IntegerField(max_length=1,default=0)
    comments = models.ManyToManyField(Comments)
    tags = models.ManyToManyField(Tags)
    rating = models.IntegerField(blank=True)
    ArtDesignFashion = models.IntegerField(max_length=1, default=0, blank=True)
    Business = models.IntegerField(max_length=1, default=0, blank=True)
    Education = models.IntegerField(max_length=1, default=0, blank=True)
    Energy = models.IntegerField(max_length=1, default=0, blank=True)
    Engineering = models.IntegerField(max_length=1, default=0, blank=True)
    Entertainment = models.IntegerField(max_length=1, default=0, blank=True)
    GovernmentAndLaw = models.IntegerField(max_length=1, default=0, blank=True)
    HealthAndMedicine = models.IntegerField(max_length=1, default=0, blank=True)
    NonProfits = models.IntegerField(max_length=1, default=0, blank=True)
    Technology = models.IntegerField(max_length=1, default=0, blank=True)
    
    def __unicode__(self):
         return self.title
        
    # Every post has a handle/url used when viewing a post's page. The url needs to be Url Safe.
    def clean_title(self, title):
        url = re.sub(r'\W',"",title)
        url = url.replace("_",'')
        url = url.strip()
        
        return url

contributions/forms.py
# Summary: Forms for adding new contributions(Posts) and contributions' comments
from django.forms import ModelForm
from contributions.models import Comments, Posts

class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ('text','contribution_id')

class PostForm(ModelForm):
    class Meta:
        model = Posts
        fields = ('description','formatted_description','title')

contributions/views.py
# Summary: Views for viewing, adding, editing contributions and contributions' comments.
import json
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import authenticate, login
from contributions.forms import CommentForm, PostForm
from contributions.models import Comments, Posts
from tags.models import Tags
from userProfile.models import Points, Profile
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime
import time

class AddContributionView(generic.TemplateView):
    # View for creating/adding a new contribution(aka experience post).
    template_name = 'contributions/add_contribution.html'

class EditContributionView(generic.DetailView):
    # View for editing an existing contribution(aka experience post).
    model = Posts
    context_object_name = "post"
    template_name = 'contributions/edit_contribution.html'

class MultiContributionView(generic.ListView):
    # View for multiple contributions(the default home page).
    template_name = 'contributions/multi_contributions.html'
    context_object_name = 'contributions'
    queryset = Posts.objects.prefetch_related('user','tags').filter(type = "experience").order_by('-rating')[:10]
    
    def get_context_data(self, **kwargs):
        context = super(MultiContributionView, self).get_context_data(**kwargs)
        context["points"] = Points.objects.prefetch_related('user').order_by('-total')[:5]
        if self.request.user.is_authenticated():
            context["authenticated"] = True
        else:
            context["authenticated"] = False
        return context

class SingleContributionView(generic.DetailView):
    # View for a single contribution(aka experience post).
    context_object_name = 'post'
    template_name = 'contributions/single_contribution.html'
    
    def get_object(self,**kwargs):
        return Posts.objects.get(pk=self.kwargs["pk"])
    
    def get_context_data(self, **kwargs):
        context = super(SingleContributionView, self).get_context_data(**kwargs)
        context["user_id"] = self.request.user.id
        context["post_comments"] = Comments.objects.prefetch_related('user').filter(contribution_id = self.kwargs["pk"])
        if self.request.user.is_authenticated():
            context["authenticated"] = True
        else:
            context["authenticated"] = False
        return context
     

class SaveNewPostForm(generic.FormView):
    # Save new contributions(aka experience posts). Return data via json if it's an AJAX request.
    form_class = PostForm

    def render_to_json_response(self, context, **response_kwargs):
        data = json.dumps(context)
        response_kwargs['content_type'] = 'application/json'
        return HttpResponse(data, **response_kwargs)

    def form_invalid(self, form):
        if self.request.is_ajax():
            return self.render_to_json_response(form.errors, status=400)
        else:
            # Request must be made via Ajax. If error redirect to home feed.
            return HttpResponseRedirect(reverse('feed:post_list')) 

    def form_valid(self, form):
        if self.request.is_ajax():       
            tag_name = self.request.POST["tag"]
            # Is this a brand new tag or did a user select a tag that already exists in the database?
            tag_type = self.request.POST["tag_type"]
            
            # If it's a new tag, save it.
            if tag_type == "new":
                tag = Tags(name=tag_name)
                tag.handle = tag.clean_handle(tag_name)
                tag.save()
            else:
                tag = Tags.objects.get(name=tag_name)
            
            # Save the post and format the title to make it url safe.
            title = form.cleaned_data["title"]
            user_id = self.request.user.id
            date_created = int(time.time())            
            post = Posts(title=title,description=form.cleaned_data["description"],formatted_description=form.cleaned_data["formatted_description"],user_id=user_id, type="experience", date_created = date_created)
            post.save()
            title_url = post.clean_title(title)
            post.url = title_url
            post.save()
            post.tags.add(tag)
            
            # Return data.
            data = {
                'post_pk': post.id,
                'post_url': post.url
            }
            return self.render_to_json_response(data)
        else:
            # Request must be made via Ajax. If error redirect to home feed.
            return HttpResponseRedirect(reverse('feed:post_list'))  

class SaveExistingPostForm(generic.FormView):
    # Save edits made to an existing contribution(aka experience post). Return json if post is made via AJAX.
    form_class = PostForm

    def render_to_json_response(self, context, **response_kwargs):
        data = json.dumps(context)
        response_kwargs['content_type'] = 'application/json'
        return HttpResponse(data, **response_kwargs)

    def form_invalid(self, form):
        if self.request.is_ajax():
            return self.render_to_json_response(form.errors, status=400)
        else:
            # Request must be made via Ajax. If error redirect to home feed.
            return HttpResponseRedirect(reverse('feed:post_list')) 

    def form_valid(self, form):
        if self.request.is_ajax():
            # Verify a pk has been sent for the Post to be edited
            if "post_id" in self.request.POST:
                pk = self.request.POST["post_id"]
                # Verify the creator of this experience is the one that is editing it
                post = Posts.objects.get(pk=pk)
                if post.user.id == self.request.user.id:  
                    # Determine what field to update 
                    title = form.cleaned_data["title"]
                    description = form.cleaned_data["description"]
                    formatted_description = form.cleaned_data["formatted_description"]
                    
                    if title == post.title:
                        # Title has not been altered, update the descriptions
                        post.formatted_description = formatted_description
                        post.description = description
                        post.save(update_fields=['description','formatted_description'])
                    else:
                        url = post.clean_title(title)
                        post.url = url
                        post.title = title
                        post.save(update_fields=['title','url'])
                    
                    # Return data
                    data = {
                        'message': "Successfully updated this experience",
                        'status': 200,
                        'post_url': post.url
                    }
                    return self.render_to_json_response(data)
                    
                else:
                    return HttpResponse("Access forbidden.", status=403)
                
            else:
                return HttpResponse("Primary Key for post not provided.", status=400)
        else:
            # Request must be made via Ajax. If error redirect to home feed.
            return HttpResponseRedirect(reverse('feed:post_list'))  

def CommentPost(request):
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            profile = Profile.objects.get(pk=request.user.id)
            contribution_id = form.cleaned_data["contribution_id"]
            text = form.cleaned_data["text"]
            date_created = int(time.time())
            newComment = Comments(contribution_id =contribution_id, user=profile, text=text, date_created=date_created)
            newComment.save()
            
            post = Posts.objects.get(pk=contribution_id)
            post.comments.add(newComment)
            
            if request.is_ajax():
                return render(request, 'contributions/comment.html', {'comment': newComment})
            else:
                return HttpResponseRedirect(reverse('contributions:detail', kwargs={'title':profile.fname, 'pk':contribution_id}))

        else:
            if request.is_ajax():
                return HttpResponse("Unable to save.")


    return HttpResponseRedirect( reverse('contributions:post_list') )

def CommentRemove(request):
    if request.POST:
        comment_id = request.POST["comment_id"]
        user_id = request.user.id;
        try:
            comment = Comments.objects.get(pk = comment_id)
            # Make sure person deleting is the commentor
            if comment.user.id == user_id:
                post = Posts.objects.get(pk = comment.contribution_id)
                post.comments.remove(comment)
                comment.delete()
                if request.is_ajax():
                    return HttpResponse("Success. Comment removed.")
                else:
                    return HttpResponseRedirect(reverse('contributions:detail', kwargs={'title':post.url, 'pk':comment.contribution_id}))
            else:
                if request.is_ajax():
                    return HttpResponse("Comment remove failed. Unauthorized access attempt.", status=403)
                else:
                    return HttpResponseRedirect(reverse('feed:post_list'))

        except:
            return HttpResponseRedirect(reverse('feed:post_list'))
            
    return HttpResponseRedirect( reverse('contributions:post_list') )

contributions/templates/contributions/comment.html
{% load url from future %}

<li>
	<div class="author">
		<div class="image-holder-round">
			<a href="{% url 'userProfile:story' comment.user.handle  comment.user.id %}">
				<img src="https://d3op517cq3iurb.cloudfront.net/{{ comment.user.pic }}" />
			</a>
		</div>
		<p>
			<a href="{% url 'userProfile:story' comment.user.handle comment.user.id %}">
				{{ comment.user.fname }} {{ comment.user.lname }}
				{% if comment.user.title != "" %}
					| {{ comment.user.title }}
				{% elif comment.user.type != "" %}
					| {{ comment.user.type }}
				{% endif %}
			</a>
		</p>
	</div>
	<p class="volk-font full-text">{% autoescape off %} {{comment.text | linebreaksbr}} {% endautoescape %}</p>
	<div class="remove-item">
		<form class="comment-remove-form" action="{% url 'contributions:comment_remove' %}" method="POST">
			<input id="comment_id" name="comment_id" type="hidden" value="{{ comment.id }}">
			<input type="submit" value="Delete Comment"></input>
			{% csrf_token %}
		</form>
	</div>
</li>

contributions/templates/contributions/multi_contributions.html
{% extends "core/base.html" %}
{% load url from future %}
{% load staticfiles %}

{% block content %}
{% if authenticated == False %}
	{% include "core/topNav_detail_out.html" %}
{% else %}
	{% include "core/topNav_detail_in.html" %}
{% endif %}
<div class="content">
	<div class="content-inner">
		<div class="welcome-holder">
			<div class="welcome-holder-left">
				<h1 class="merri-font">Welcome to <span style="color:#316868">Lend Experience</span></h1>
				<p class="merri-font">The best source for first-hand career knowledge.</br>Start exploring or become a <a href="{% url 'accounts:signup' %}">contributor</a>.</p>
				{% if authenticated == False %}
					<a class="actionButton seagreen-button-flat" href="{% url 'accounts:signup' %}">Sign Up</a>
					<a class="actionButton grey-button-flat" href="{% url 'accounts:login' %}">Login</a>
				{% endif %}
			</div>
			<div class="welcome-holder-right" {% if authenticated == False %} style="margin:18px 21px 0px 0px" {% endif %}>
				<div class="tile" data-toggle="tooltip" data-placement="top" title="Engineering">
					<a href="{% url 'careers:career' 'Engineering' %}"><img src="https://d2usanuqr4r7y2.cloudfront.net/images/careers/engineering1.jpg"></a>
				</div>
				<div class="tile" data-toggle="tooltip" data-placement="top" title="Energy">
					<a href="{% url 'careers:career' 'Energy' %}"><img src="https://d2usanuqr4r7y2.cloudfront.net/images/careers/energy1.jpg"></a>
				</div>
				<div class="tile" data-toggle="tooltip"data-placement="top" title="Education">
					<a href="{% url 'careers:career' 'Education' %}" ><img src="https://d2usanuqr4r7y2.cloudfront.net/images/careers/education4.jpg"></a>
				</div>
				<div class="tile" data-toggle="tooltip" data-placement="top" title="Business">
					<a href="{% url 'careers:career' 'Business' %}"><img src="https://d2usanuqr4r7y2.cloudfront.net/images/careers/marketing1.jpg"></a>
				</div>
				<div class="tile" data-toggle="tooltip" data-placement="top" title="Art, Design & Fashion">
					<a href="{% url 'careers:career' 'ArtDesignFashion' %}"><img src="https://d2usanuqr4r7y2.cloudfront.net/images/careers/fashion3.jpg"></a>
				</div>
				<div class="tile" data-toggle="tooltip"data-placement="bottom" title="Science & Technology">
					<a href="{% url 'careers:career' 'Technology' %}" ><img src="https://d2usanuqr4r7y2.cloudfront.net/images/careers/science1.jpg"></a>
				</div>
				<div class="tile" data-toggle="tooltip" data-placement="bottom" title="NonProfits">
					<a href="{% url 'careers:career' 'NonProfits' %}"><img src="https://d2usanuqr4r7y2.cloudfront.net/images/careers/nonprofit4.jpg"></a>
				</div>
				<div class="tile" data-toggle="tooltip" data-placement="bottom" title="Health & Medicine">
					<a href="{% url 'careers:career' 'HealthAndMedicine' %}"><img src="https://d2usanuqr4r7y2.cloudfront.net/images/careers/medicine2.jpg"></a>
				</div>
				<div class="tile" data-toggle="tooltip" data-placement="bottom" title="Government & Law">
					<a href="{% url 'careers:career' 'GovernmentAndLaw' %}"><img src="https://d2usanuqr4r7y2.cloudfront.net/images/careers/gov1.jpg"></a>
				</div>
				<div class="tile" data-toggle="tooltip" data-placement="bottom" title="Entertainment">
					<a href="{% url 'careers:career' 'Entertainment' %}"><img src="https://d2usanuqr4r7y2.cloudfront.net/images/careers/entertainment2.jpg"></a>
				</div>
			</div>
		</div>
		<script type="text/javascript"> 
			$(document).ready(function(){
				$(".limited-text").dotdotdot({height:65});
				$('.tile').tooltip()
			})
		</script>
		{% if contributions %}
			<div class="content-item-list">
				<h2 class="content-title volk-font">Top Experiences</h2>
				{% for post in contributions %}
					<div class="content-item" id="post_{{post.id}}">
						<div class="author">
							<div class="image-holder-round">
								<a href="{% url 'userProfile:story' post.user.handle post.user.id %}">
									<img src="https://d3op517cq3iurb.cloudfront.net/{{ post.user.pic }}" />
								</a>
							</div>			
							<p>
								<a href="{% url 'userProfile:story' post.user.handle post.user.id %}">{{ post.user.fname }} {{ post.user.lname }}
									{% if post.user.title != "" %}
										| {{ post.user.title }}
									{% elif post.user.type != "" %}
										| {{ post.user.type }}
									{% endif %}
								</a>
							</p>		
						</div>
						<h1 class="volk-font"><a href="{% url 'contributions:detail' post.url post.id %}">{{ post.title }}</a></h1>
						<p class="volk-font limited-text">{{ post.description }}</p>
						<div class="tag-holder">
							{% for tag in post.tags.all %}
								<a class="tag volk-font grey-button-flat" href="{% url 'tagDetail:tagView' tag.handle tag.id %}">{{ tag.name }} </a>
							{% endfor %}
						</div>
					</div>
				{% endfor %}
			</div>
		{% else %}
			<p>No contributions were found!</p>
		{% endif %}
		<div class="content-side-bar">
			<h2 class="content-title">Top Contributors</h2>
			{% for point in points %}
			<div class="side-item">
				<div class="image-holder-small">
					<img src="https://d3op517cq3iurb.cloudfront.net/{{ point.user.pic }}" />
				</div>
				<p><a href="{% url 'userProfile:story' point.user.handle point.user.id %}">{{ point.user.fname }} {{ point.user.lname }}</a></p>
			</div>
			{% endfor %}
		</div>
	</div>
</div>

{% endblock %}

contributions/templates/contributions/single_contribution.html
{% extends "core/base.html" %}
{% load url from future %}

{% block content %}

{% if authenticated == False %}
	{% include "core/topNav_detail_out.html" %}
{% else %}
	{% include "core/topNav_detail_in.html" %}
{% endif %}
<div class="content">
	<div class="content-inner">
		<div class="content-item-list">
			<div class="content-item single-content-item" id="post_{{ post.id }}" style="border-bottom:2px solid #DBDBDB">
				<input type="hidden" id="post_pk" value="{{ post.id }}">
				{% with tags=post.tags.all %}
					<div class="tag-holder tag-holder-alt">
						<!--<a class="category hell-font"></a>-->
						<div id="current-tags">
							{% if tags %}
								{% for tag in tags %}
									<a id="tag_{{ tag.id }}"class="tag volk-font grey-button-flat" href="{% url 'tagDetail:tagView' tag.handle tag.id %}">{{ tag.name }}</a>
								{% endfor %}
							{% else %}
								<p id="no_tag_alert" class="volk-font" style="width:auto;float:left;margin-right:10px;">This experience has no career tags.</p>
							{% endif %}
						</div>
						{% if authenticated == True %}
							<a class="edit-tag">Edit <i class="icon-edit"></i></a>
						{% endif %}
					</div>
					<div class="tag-holder tag-holder-alt blank">
						<div id="tags-to-remove">
							{% for tag in tags %}
								<form class="tag_remove_form" action="{% url 'tags:removeTag' %}" method="POST">
									<input type="hidden" name="tag_id" value="{{ tag.id }}"/>
									<input type="hidden" name="contribution_id" value="{{ post.id }}"/>
									<p class="tag-edit volk-font">
										<span class="tag-edit-text">{{ tag.name }}</span>
										<button type="submit" class="close">×</button>
									</p>
									{% csrf_token %}
								</form>
							{% endfor %}
						</div>
						<div class="tag-new">
							<form id="tag_search_form" method="POST" action="{% url 'tags:search' %}">
								<input type="text" name="tag_text" id="tag_text" placeholder="Search Tags" />
								<input type="hidden" name="contribution_id" value="{{ post.id }}"/>
								{% csrf_token %}
							</form>
							<a class="cancel lightgrey-button-flat">Finished</a>
							<div class="tag-search-box blank">
								<div id="tag-search-results">
									<p class="hell-font">Begin typing to search existing tags or add a new one.</p>
								</div>
							</div>
						</div>
					</div>
				{% endwith %}
				<div class="author">
					<div class="image-holder-round">
						<a href="{% url 'userProfile:story' post.user.handle post.user.id %}"><img src="https://d3op517cq3iurb.cloudfront.net/{{ post.user.pic }}" /></a>
					</div>
					<p>
						<a href="{% url 'userProfile:story' post.user.handle post.user.id %}">
							{{ post.user.fname }} {{ post.user.lname }}
							{% if post.user.title != "" %}
								| {{ post.user.title }}
							{% elif post.user.type != "" %}
								| {{ post.user.type }}
							{% endif %}
						</a>
					</p>
				</div>
				<h1 class="volk-font">
					<span>{{ post.title }}</span>
					{% if post.user.id == user_id %}
						<a class="edit" href="{% url 'contributions:edit' post.url post.id %}">Edit <i class="icon-edit"></i></a></h1>
					{% endif %}
				</h1>
				{% if post.formatted_description == "" %}
					<p class="volk-font full-text">{% autoescape off %} {{ post.description | linebreaksbr }} {% endautoescape %}</p>
				{% else %}
					<div class="volk-font full-text">{% autoescape off %} {{ post.formatted_description }} {% endautoescape %}</div>
				{% endif %}
			</div>
			{% with comments=post_comments %}
				{% if authenticated == True %}
					<div class="comment-action">
						<div class="comment-action-head">
							{% with comment_count=comments.count %}
								{% if comment_count == 1 %}
									<p><strong>{{ comment_count }}</strong> Response</p>
								{% else %}
									<p><strong>{{ comment_count }}</strong> Responses</p>
								{% endif %}
							{% endwith %}
							<p><strong>Contribute a Response</strong></p>
						</div>
						<div class="comment-result"></div>
						<div class="comment-input-fake">
							<textarea id="fake-comment-input" placeholder="Click to contribute your response..."></textarea>
						</div>
						<div class="comment-input-real blank">						
							<form id="comment-form" action="{% url 'contributions:comment_save' %}" method="post">
								<textarea id="text" name="text" placeholder="Start typing..."></textarea>
								<input id="contribution_id" name="contribution_id" type="hidden" value="{{ post.id }}">
								<input type="submit" value="Add Response" class="submitCommentButton seagreen-button-flat" />
								{% csrf_token %}
							</form>
						</div>
					</div>
				{% endif %}
				<ul class="comment-list">
					{% for comment in comments.all %}
						<li>
							<div class="author">
								<div class="image-holder-round">
									<a href="{% url 'userProfile:story' comment.user.handle comment.user.id %}">
										<img src="https://d3op517cq3iurb.cloudfront.net/{{ comment.user.pic }}" />
									</a>
								</div>
								<p>
									<a href="{% url 'userProfile:story' comment.user.handle comment.user.id %}">
										{{ comment.user.fname }} {{ comment.user.lname }}
										{% if comment.user.title != "" %}
										| {{ comment.user.title }}
										{% elif comment.user.type != "" %}
										| {{ comment.user.type }}
										{% endif %}
									</a>
								</p>
							</div>
							<p class="volk-font full-text">{% autoescape off %} {{ comment.text | linebreaksbr }} {% endautoescape %}</p>
							{% if user_id == comment.user.id %}
								<div class="remove-item">
									<form class="comment-remove-form" action="{% url 'contributions:comment_remove' %}" method="POST">
										<input id="comment_id" name="comment_id" type="hidden" value="{{ comment.id }}">
										<input type="submit" value="Delete Comment"></input>
										{% csrf_token %}
									</form>
								</div>
							{% endif %}
						</li>
					{% endfor %}
				</ul>
			{% endwith %}
		</div>
	</div>
</div>
<script type="text/javascript"> 
	var page = "singleContribution";
</script>
{% endblock %}