contributions/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from contributions import views

urlpatterns = patterns('',
    url(r'^$', views.MultiContributionView.as_view(), name="post_list"),
    url(r'^(?P<title>[0-9A-Za-z]+)-(?P<pk>\d+)/$', views.SingleContributionView.as_view(), name='detail'),
    url(r'^add/$', login_required(views.AddContributionView.as_view()), name='post'),
    url(r'^edit/(?P<title>[0-9A-Za-z]+)-(?P<pk>\d+)/$', login_required(views.EditContributionView.as_view()), name='edit'),
    url(r'^save_new/$', login_required(views.SaveNewPostForm.as_view()), name='saveNewPost'),
    url(r'^save_existing/$', login_required(views.SaveExistingPostForm.as_view()), name='saveExistingPost'),
    url(r'^comment/save/$', login_required(views.CommentPost), name='comment_save'),
    url(r'^comment/remove/$', login_required(views.CommentRemove), name='comment_remove'),
)

lxp/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from userProfile import views
from siteInfo import views
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('contributions.urls', namespace="feed")),
    url(r'^contributions/', include('contributions.urls', namespace="contributions")),
    url(r'^about/', views.AboutView.as_view(), name='about'),
    url(r'^accounts/', include('accounts.urls',namespace="accounts")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^career/', include('careers.urls',namespace="careers")),
    url(r'^community/', views.CommunityView.as_view(), name='community'),
    url(r'^contact/', views.ContactView.as_view(), name='contact'),
    url(r'^legal/', views.LegalView.as_view(), name='legal'),
    url(r'^tags/', include('tags.urls',namespace="tags")),
    url(r'^story/', include('userProfile.urls',namespace="myUserProfile")),
    url(r'^search/', include('search.urls',namespace="search")),
    
    #url(r'^info/', include('about.urls',namespace="siteInfo")),
    
    
    url(r'^(?P<tag>[0-9A-Za-z]+)-(?P<pk>[0-9]+)/', include('tags.urls',namespace="tagDetail")),
    url(r'^(?P<handle>[0-9A-Za-z]+)_(?P<pk>[0-9]+)/', include('userProfile.urls',namespace="userProfile")),
    
)

tags/urls.py
from django.conf.urls import patterns, url
from tags import views

urlpatterns = patterns('',
    url(r'^$', views.TagsView.as_view(), name='tagView'),
    url(r'^search/$', views.Search.as_view(), name='search'),
    url(r'^save/$', views.SaveTag, name='saveTag'),
    url(r'^remove/$', views.RemoveTag, name='removeTag'),
)

userProfile/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from userProfile import views

urlpatterns = patterns('',
    url(r'^$', views.Story.as_view(), name="story"),
    url(r'^edit/$', login_required(views.EditStory.as_view()), name="edit"),
    url(r'^edit/save/$', login_required(views.Update.as_view()), name="saveEdit"),
    url(r'^edit/image/$', login_required(views.ImageUpload.as_view()), name="uploadImage"),
    url(r'^view/$', login_required(views.Story.as_view()), name="mystory"),
)

tags/models.py
from django.db import models
import re

class Tags(models.Model):
    name = models.CharField(max_length=70, blank=True)
    handle = models.CharField(max_length=70, blank=True)
    
    # Every tag has a handle used when viewing a tag page. The handle needs to be Url Safe.
    def clean_handle(self, handle):
        handle = re.sub(r'\W',"",handle)
        handle = handle.replace("_",'')
        handle = handle.strip()
        
        return handle

tags/views.py
# Summary: View posts related to tags, search tags, create tags and delete tags.
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from tags.tagSearch import SearchTags, ManageTags
from contributions.models import Posts
from tags.models import Tags

class TagsView(generic.ListView):
    template_name = 'tags/detail.html'
    context_object_name = 'post_list'
    paginate_by = 10
    
    def get_queryset(self, **kwargs):
        # Get the posts that have been assigned this tag.
        pk = self.kwargs["pk"]
        self.tag = Tags.objects.get(pk = pk)
        queryset = Posts.objects.prefetch_related('user','tags').filter(tags = self.tag)
        return queryset
        
    def get_context_data(self, **kwargs):
        context = super(TagsView, self).get_context_data(**kwargs)
        context["tag"] = self.tag
        if self.request.user.is_authenticated():
            context["authenticated"] = True
        else:
            context["authenticated"] = False
        
        return context

class Search(generic.View):  
    def post(self, request, *args, **kwargs):
        searchStr = request.POST["tag_text"]
        if searchStr != "":
            searchResults = SearchTags(searchStr).search()
            # Determine whether a new post is being created with a single tag or if tags are being added to an existing post.
            if "contribution_id" in request.POST.keys():
                contribution_id = request.POST["contribution_id"]
                searchDict = {}
                searchDict["string"] = searchStr
                searchDict["contribution_id"] = contribution_id
                # If tags are being added to existing posts, return HTML of just the tags.
                return render(request, 'tags/searchResult.html', {'results': searchResults, 'search': searchDict})
            else:
                # If tag is being added with the creation of a new post, send back this html.
                return render(request, 'tags/searchResult_newContribution.html', {'results': searchResults, 'search': searchDict})
        else:
            return HttpResponse(400)
            
    def get(self, request, *args, **kwargs):
        return HttpResponse(400)

@login_required
def SaveTag(request):
    if request.POST:
        type = request.POST["type"]
        tag = request.POST["tag_text"]
        contribution_id = request.POST["contribution_id"]
        post = Posts.objects.get(pk=contribution_id)
        title = post.title.replace(" ", "")
        
        if type is not None and tag is not None and contribution_id is not None:
            if type == "new":
                #Save to tags_tags
                tagLib = Tags(name=tag)
                tagLib.handle = tagLib.clean_handle(tag)
                tagLib.save()
            else:
                tagLib = Tags.objects.get(name = tag)
                
            #save to posts_tags
            post.tags.add(tagLib)
            post.save()
            #add to Redis Tags
            redis = ManageTags(tag)
            redis.add()
            
            if request.is_ajax():
                return render(request, 'tags/tag.html', {'tag': tagLib})
            else:
                return HttpResponseRedirect(reverse('singleCont:detail', kwargs={'pk': contribution_id, 'title': title} ))
        
        else: 
            if request.is_ajax():
                HttpResponse(400)
            else:
                return HttpResponseRedirect(reverse('singleCont:detail', kwargs={'pk': contribution_id, 'title': title} ))

    return HttpResponseRedirect(reverse('contributions:post_list'))

@login_required
def RemoveTag(request):
    if request.POST:
        contribution_id = request.POST["contribution_id"]
        tag_id = request.POST["tag_id"]
        
        try:
            tag = Tags.objects.get(pk=tag_id)
            post = Posts.objects.get(pk=contribution_id)
            
            #remove post_tags
            post.tags.remove(tag)
            
            if request.is_ajax():
                return HttpResponse("Success. Comment removed.")
            else:
                title = post.title.replace(" ", "")
                return HttpResponseRedirect(reverse('singleCont:detail', kwargs={'pk': contribution_id, 'title': title} ))

        except:
            if request.is_ajax():
                return HttpResponse("Error. Tag not Removed.")
            else:
                return HttpResponseRedirect(reverse('contributions:post_list'))
            
            
    return HttpResponseRedirect(reverse('contributions:post_list'))

tags/templates/tags/detail.html
{% extends "core/base.html" %}
{% load url from future %}
{% load staticfiles %}

{% block content %}
{% if authenticated == False %}
	{% include "core/topNav_detail_out.html" %}
{% else %}
	{% include "core/topNav_detail_in.html" %}
{% endif %}

<script type="text/javascript"> 
	var page = "career";
	var career_url = "career/{{ career.name }}";
</script>
<div class="content">
	<div class="content-inner">
		<div class="content-item-list">
			<div class="content-title-box">
				<h3 class="title-left merri-font">{{ tag.name }}</h3>
				<span class="count-right volk-font" >{{ post_list.count }} Contribution(s)</span>
			</div>
			{% for post in post_list %}
			<div class="content-item" id="post_{{post.id}}">
				<div class="author">
					<div class="image-holder-round">
						<a href="{% url 'userProfile:story' post.user.handle post.user.id %}"><img src="https://d3op517cq3iurb.cloudfront.net/{{ post.user.pic }}" /></a>
					</div>				
					<p><a href="{% url 'userProfile:story' post.user.handle post.user.id %}">{{ post.user.fname }} {{ post.user.lname }}
					{% if post.user.title != "" %}
						| {{ post.user.title }}
					{% elif post.user.type != "" %}
						| {{ post.user.type }}
					{% endif %}</a></p>
				</div>				
				<h1 class="volk-font"><a href="{% url 'contributions:detail' post.url post.id %}">{{ post.title }}</a></h1>
				<p class="volk-font limited-text">{{ post.description }}</p>
				<div class="tag-holder">
					{% for tag in post.tags.all %}
						<a class="tag volk-font grey-button-flat" href="{% url 'tagDetail:tagView' tag.handle tag.id %}">{{ tag.name }}</a>
					{% endfor %}
				</div>
			</div>
			{% endfor %}
			{% if is_paginated %}
				<div class="pagination">
		            <span class="page-links">
		                {% if page_obj.has_previous %}
		                    <a href="{% url 'tagDetail:tagView' tag.handle tag.id %}?page={{ page_obj.previous_page_number }}">previous</a>
		                {% endif %}
		                <span class="page-current">
		                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
		                </span>
		                {% if page_obj.has_next %}
		                    <a href="{% url 'tagDetail:tagView' tag.handle tag.id %}?page={{ page_obj.next_page_number }}">next</a>
		                {% endif %}
		            </span>
		        </div>
			{% endif %}
		</div>
		<div class="content-side-bar">
			<a class="seagreen-button-flat contribute-button" href="{% url 'contributions:post' %}">Contribute your Experiences</a>
		</div>
	</div>
</div>
{% endblock %}

tags/templates/tags/searchResult.html
{% load url from future %}

{% if results %}
{% for result in results %}
<form class="new_tag_form" method="POST" action="{% url 'tags:saveTag' %}">
	<input type="hidden" name="tag_text" value="{{ result }}"/>
	<input type="hidden" name="contribution_id" value="{{ search.contribution_id }}"/>
	<input type="hidden" name="type" value="old"/>
	<input type="submit" name="newTag" class="newTagSubmit" value="{{ result }}"/>
	{% csrf_token %}
</form>
{% endfor %}
{% else %}
<form class="new_tag_form" method="POST" action="{% url 'tags:saveTag' %}">
	<p>Create New Tag <span style="color:#0E4141">{{ search.string }}</span></p>
	<input type="hidden" name="tag_text" value="{{ search.string }}"/>
	<input type="hidden" name="contribution_id" value="{{ search.contribution_id }}"/>
	<input type="hidden" name="type" value="new"/>
	<input type="submit" name="newTag" class="newTagSubmit" value="{{ search.string }} "/>
	{% csrf_token %}
</form>
{% endif %}

tags/templates/tags/searchResult_newContribution.html
{% load url from future %}

{% if results %}
{% for result in results %}
	<input type="submit" name="newTag" class="newTagSubmit career-topic-result" data-type="old" value="{{ result }}"/>
{% endfor %}
{% else %}
	<p>Create New Tag <span style="color:#0E4141">{{ search.string }}</span></p>
	<input type="submit" name="newTag" class="newTagSubmit career-topic-result" data-type="new" value="{{ search.string }} "/>
{% endif %}

tags/templates/tags/tag.html
{% load url from future %}
<a id="tag_{{ tag.id }}"class="tag volk-font grey-button-flat" href="{% url 'tagDetail:tagView' tag.handle tag.id %}">{{ tag.name }}</a>
`
<form class="tag_remove_form" action="{% url 'tags:removeTag' %}" method="POST">
	<input type="hidden" name="tag_id" value="{{ tag.id }}"/>
	<input type="hidden" name="contribution_id" value="{{ tag.contribution_id }}"/>
	<p class="tag-edit volk-font" href="">
		<span class="tag-edit-text">{{ tag.name }}</span>
		<button type="submit" class="close">×</button>
	</p>
	{% csrf_token %}
</form>