accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
    url(r'^login/', 'django.contrib.auth.views.login', name="login"),
    url(r'^logout/', 'django.contrib.auth.views.logout',{'next_page': '/accounts/login/'}, name="logout"),
    url(r'^signup/$', views.SignUp.as_view(), name="signup"),
    url(r'^signup/success/$', views.signupSuccess, name="signup_success"),
    url(r'^signup/error/$', views.signupError, name="signup_error"),
    url(r'^user/password/reset/$','django.contrib.auth.views.password_reset', {'post_reset_redirect' : 'done'}, name="password_reset"),
    url(r'^user/password/reset/done/$','django.contrib.auth.views.password_reset_done', name="reset_done"),
    url(r'^user/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/accounts/user/password/done/'}),
    url(r'^user/password/done/$', 'django.contrib.auth.views.password_reset_complete'),
)

careers/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from careers import views

urlpatterns = patterns('',
    url(r'^categorize$', login_required(views.Categorize.as_view()), name="categorize"),
    url(r'^(?P<careerCategory>[0-9A-Za-z]+)$', views.Career.as_view(), name="career")
)

contributions/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from contributions import views

urlpatterns = patterns('',
    url(r'^$', views.MultiContributionView.as_view(), name="post_list"),
    url(r'^(?P<title>[0-9A-Za-z]+)-(?P<pk>\d+)/$', views.SingleContributionView.as_view(), name='detail'),
    url(r'^add/$', login_required(views.AddContributionView.as_view()), name='post'),
    url(r'^edit/(?P<title>[0-9A-Za-z]+)-(?P<pk>\d+)/$', login_required(views.EditContributionView.as_view()), name='edit'),
    url(r'^save_new/$', login_required(views.SaveNewPostForm.as_view()), name='saveNewPost'),
    url(r'^save_existing/$', login_required(views.SaveExistingPostForm.as_view()), name='saveExistingPost'),
    url(r'^comment/save/$', login_required(views.CommentPost), name='comment_save'),
    url(r'^comment/remove/$', login_required(views.CommentRemove), name='comment_remove'),
)

lxp/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from userProfile import views
from siteInfo import views
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('contributions.urls', namespace="feed")),
    url(r'^contributions/', include('contributions.urls', namespace="contributions")),
    url(r'^about/', views.AboutView.as_view(), name='about'),
    url(r'^accounts/', include('accounts.urls',namespace="accounts")),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^career/', include('careers.urls',namespace="careers")),
    url(r'^community/', views.CommunityView.as_view(), name='community'),
    url(r'^contact/', views.ContactView.as_view(), name='contact'),
    url(r'^legal/', views.LegalView.as_view(), name='legal'),
    url(r'^tags/', include('tags.urls',namespace="tags")),
    url(r'^story/', include('userProfile.urls',namespace="myUserProfile")),
    url(r'^search/', include('search.urls',namespace="search")),
    
    #url(r'^info/', include('about.urls',namespace="siteInfo")),
    
    
    url(r'^(?P<tag>[0-9A-Za-z]+)-(?P<pk>[0-9]+)/', include('tags.urls',namespace="tagDetail")),
    url(r'^(?P<handle>[0-9A-Za-z]+)_(?P<pk>[0-9]+)/', include('userProfile.urls',namespace="userProfile")),
    
)

search/urls.py
from django.conf.urls import patterns, url
from search import views

urlpatterns = patterns('',
    url(r'^$', views.SearchAllView.as_view(), name='searchAll'),
)

userProfile/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from userProfile import views

urlpatterns = patterns('',
    url(r'^$', views.Story.as_view(), name="story"),
    url(r'^edit/$', login_required(views.EditStory.as_view()), name="edit"),
    url(r'^edit/save/$', login_required(views.Update.as_view()), name="saveEdit"),
    url(r'^edit/image/$', login_required(views.ImageUpload.as_view()), name="uploadImage"),
    url(r'^view/$', login_required(views.Story.as_view()), name="mystory"),
)

search/views.py
# Summary: Views for returning search results.
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import authenticate, login
from search.searchAlgorithm.initialize_search import search

class SearchAllView(generic.View):  
    def post(self, request, *args, **kwargs):
        searchStr = request.POST["search"]
        if searchStr != "":
            searchResults = search(searchStr)
            returnDict = {}
            returnDict["value"] = searchStr
            return render(request, 'search/searchResult.html', {'results': searchResults, 'search': returnDict})
        else:
            return HttpResponse(400)
            
    def get(self, request, *args, **kwargs):
        return HttpResponse(400)

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
   {% include "core/head.html" %}
</head>
<body>
	<div class="container">
		{% include "core/search.html" %}
        {% block content %}{% endblock %}
	</div>
	{% include "core/footer.html" %}
	{% include "core/body_javascript.html" %}
</body>
</html>

core/templates/core/base_old.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
   {% include "core/head.html" %}
</head>
<body>
	<div class="container">
    	{% include "core/topNav.html" %}
		<div class="content">
			<div class="content-inner">
        		{% block content %}{% endblock %}
			</div>
		</div>
		{% include "core/footer.html" %}
	</div>
	<script type="text/javascript" src="https://d3fuw6vo22gqor.cloudfront.net/js/placeholder.v.2.1.0.js" ></script>
</body>
</html>

core/templates/core/body_javascript.html
<!--<script type="text/javascript" src="../../../../../static/js/jquery.hotkeys.js" ></script>
<script type="text/javascript" src="../../../../../static/js/bootstrap-wysiwyg.js" ></script>
<script type="text/javascript" src="https://d3fuw6vo22gqor.cloudfront.net/js/placeholder.v.2.1.0.js" ></script>
 <script src="../../../static/js/controllers/ContributionsController.js"></script>
<script src="../../../static/js/controllers/SingleContributionController.js"></script>
	<script src="../../../static/js/controllers/StoryController.js"></script>
<script src="../../../static/js/controllers/EditStoryController.js"></script>
<script src="../../../static/js/controllers/CareerController.js"></script>
<script src="../../../static/js/controllers/AddContributionController.js"></script>
<script src="../../../static/js/controllers/EditContributionController.js"></script>
<script src="../../../static/js/controllers/CoreController.js"></script>
<script src="../../../static/js/misc.js"></script>
	<script src="../../../static/js/routers/Router.js"></script>-->
<script type="text/javascript" src="https://d2usanuqr4r7y2.cloudfront.net/js/lib/jquery.hotkeys.js" ></script>
<script type="text/javascript" src="https://d2usanuqr4r7y2.cloudfront.net/js/lib/bootstrap-wysiwyg.js" ></script>
<script type="text/javascript" src="https://d2usanuqr4r7y2.cloudfront.net/js/lib/placeholder.v.2.1.0.js" ></script>
<script src="https://d2usanuqr4r7y2.cloudfront.net/js/app/controllers/ContributionsController.js"></script>
<script src="https://d2usanuqr4r7y2.cloudfront.net/js/app/controllers/SingleContributionController.js"></script>
<script src="https://d2usanuqr4r7y2.cloudfront.net/js/app/controllers/StoryController.js"></script>
<script src="https://d2usanuqr4r7y2.cloudfront.net/js/app/controllers/EditStoryController.js"></script>
<script src="https://d2usanuqr4r7y2.cloudfront.net/js/app/controllers/CareerController.js"></script>
<script src="https://d2usanuqr4r7y2.cloudfront.net/js/app/controllers/AddContributionController.js"></script>
<script src="https://d2usanuqr4r7y2.cloudfront.net/js/app/controllers/EditContributionController.js"></script>
<script src="https://d2usanuqr4r7y2.cloudfront.net/js/app/controllers/CoreController.js"></script>
<script src="https://d2usanuqr4r7y2.cloudfront.net/js/app/misc.js"></script>
<script src="https://d2usanuqr4r7y2.cloudfront.net/js/app/routers/Router.js"></script>

	<script type="text/javascript">
		var app = app|| {};
		var ENTER_KEY = 13;
		$(window).bind('popstate',function(){return false;});
		var Router;
		$(function () {
			'use strict';
			Router = new app.Router();
			// Enable pushState for compatible browsers
			var enablePushState = true;  
		
			// Disable for older browsers (IE8, IE9 etc)
			var pushState = !!(enablePushState && window.history && window.history.pushState);
		
			if(pushState) {
				Backbone.emulateHTTP = true;
			    Backbone.history.start({
			        pushState: true
			    })
			} else {
				Backbone.history.start({
			    	pushState: false
			    })
			}
			Backbone.emulateJSON = true;
		});
	$(document).ready(function(){
		app.Core = app.CoreController;
		app.Core.init();
	})
</script>

core/templates/core/dropdowns.html
{% load url from future %}
<div id="explore-drop-down" class="blank">
  	<ul class="nav-drop-down-menu">
    	<li>
			<a href="{% url 'careers:career' 'ArtDesignFashion' %}">Art, Design & Fashion</a>
		</li>
	    <li>
			<a href="{% url 'careers:career' 'Business' %}">Business</a>
		</li>
		<li>
			<a href="{% url 'careers:career' 'Education' %}">Education</a>
		</li>
		<li>
			<a href="{% url 'careers:career' 'Energy' %}">Energy</a>
		</li>
		<li>
			<a href="{% url 'careers:career' 'Engineering' %}">Engineering</a>
		</li>
		<li>
			<a href="{% url 'careers:career' 'Entertainment' %}">Entertainment</a>
		</li>
		<li>
			<a href="{% url 'careers:career' 'GovernmentAndLaw' %}">Government & Law</a>
		</li>
		<li>
			<a href="{% url 'careers:career' 'HealthAndMedicine' %}">Health & Medicine</a>
		</li>
		<li>
			<a href="{% url 'careers:career' 'NonProfits' %}">NonProfits</a>
		</li>
		<li>
			<a href="{% url 'careers:career' 'Technology' %}">Technology</a>
		</li>
  	</ul>
</div>
<div id="myaccount-drop-down" class="blank">
  	<ul class="nav-drop-down-menu">
		<li>
			<a href="{% url 'myUserProfile:mystory' %}">My Story</a>
		</li>
		<li>
			<a href="{% url 'myUserProfile:edit' %}">Edit Story</a>
		</li>
		<li style="border-top:1px solid #eee;margin-top:10px;margin-bottom:-15px;">
			<a href="{% url 'accounts:logout' %}">Logout</a>
		</li>
	</ul>
</div>

core/templates/core/footer.html
{% load url from future %}
<div class="footer">
	<div class="footer-inner">
		<ul>
			<li>
				<a href="{% url 'about' %}">About</a>
			</li>
			<li>
				<a href="{% url 'community' %}">Communities</a>
			</li>
			<li>
				<a href="{% url 'contact'  %}">Contact</a>
			</li>
			<li>
				<a href="{% url 'legal'  %}">Legal</a>
			</li>
		</ul>
		<p>© 2013 Lend Experience, Inc. All rights reserved.</p>
	</div>
</div>

core/templates/core/head.html
<title>Lend Experience</title>
{% load staticfiles %}
<link rel="shortcut icon" href="https://d3fuw6vo22gqor.cloudfront.net/images/logos/le16.ico">
<link rel="stylesheet" type="text/css" href="https://d2usanuqr4r7y2.cloudfront.net/css/bootstrap/css/bootstrap.css" />
<link rel="stylesheet" type="text/css" href="https://d2usanuqr4r7y2.cloudfront.net/css/buttons.css" />
<link rel="stylesheet" type="text/css" href="https://d2usanuqr4r7y2.cloudfront.net/css/misc.v.1.0.css" />
<!--<link rel="stylesheet" type="text/css" href="../../../../static/css/base.v.1.0.css" />-->
<link rel="stylesheet" type="text/css" href="https://d2usanuqr4r7y2.cloudfront.net/css/base.v.1.0.css" />
<script type="text/javascript" src="https://d2usanuqr4r7y2.cloudfront.net/js/lib/jquery.js" ></script>
<script type="text/javascript" src="https://d2usanuqr4r7y2.cloudfront.net/js/lib/hexorator.min.js" ></script>
<script type="text/javascript" src="https://d2usanuqr4r7y2.cloudfront.net/js/lib/underscore.js" ></script>
<script type="text/javascript" src="https://d2usanuqr4r7y2.cloudfront.net/js/lib/backbone.js" ></script>
<script type="text/javascript" src="https://d2usanuqr4r7y2.cloudfront.net/js/lib/bootstrap.js" ></script>
<script type="text/javascript" src="https://d2usanuqr4r7y2.cloudfront.net/js/lib/autoellipsis.js" ></script>
<link href='https://fonts.googleapis.com/css?family=PT+Mono' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Ubuntu:300" rel="stylesheet" type="text/css">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
<script type="text/javascript">
	var page;
</script>

core/templates/core/search.html
<div class="search-result-container blank">
	<div>
		<div>
			<ul id="search_result_list_holder">
				<p class='noResult'>Start typing to begin your search. Search people, career experiences and career topics.</p>
			</ul>
		</div>
	</div>
</div>

core/templates/core/sideNav.html
<div class="side-nav">
	<div>
		<h1>J.Myers</h1>
		<ul>
			<li>
				<span></span>
				<a href="../../about">ABOUT</a> 
			</li>
			<li>
				<span></span>
				<a href="../../">BLOG</a> 
			</li>
			<li>
				<span></span>
				<a href="https://github.com/jfmyers" target="_blank">CODE</a> 
			</li>
			<li>
				<span></span>
				<a href="../../projects">PROJECTS</a> 
			</li>
			<li>
				<span></span>
				<a href="../../research">RESEARCH</a> 
			</li>
		</ul>
	</div>
</div>

core/templates/core/topNav.html
{% load url from future %}
<div class="top-nav">
	<div class="top-nav-inner">
		<img class="logo" src="https://d3fuw6vo22gqor.cloudfront.net/images/logos/le75.png" />
		<a href="#"class="tab toggle-nav-drop-down">
			<span>Explore ▾</span>
		</a>
		<div class="vertical-divider"></div>
		<a class="tab" href="{% url 'contributions:post' %}">
			<span>Contribute</span>
		</a>
		<div class="vertical-divider"></div>
		<a class="tab">
			<span>Learn More</span>
		</a>
		<div class="vertical-divider"></div>
		<div class="search">
			<input type="text" placeholder="Search Career Experiences" />
		</div>
	</div>
</div>

<div id="explore-drop-down" class="blank">
  	<ul class="nav-drop-down-menu">
    	<li>
			<a href="{% url 'contributions:category' 'artdesignfashion' %}">Art, Design & Fashion</a>
		</li>
	    <li>
			<a href="{% url 'contributions:category' 'business' %}">Business</a>
		</li>
		<li>
			<a href="{% url 'contributions:category' 'education' %}">Education</a>
		</li>
		<li>
			<a href="{% url 'contributions:category' 'energy' %}">Energy</a>
		</li>
		<li>
			<a href="{% url 'contributions:category' 'engineering' %}">Engineering</a>
		</li>
		<li>
			<a href="{% url 'contributions:category' 'entertainment' %}">Entertainment</a>
		</li>
		<li>
			<a href="{% url 'contributions:category' 'governmentlaw' %}">Government & Law</a>
		</li>
		<li>
			<a href="{% url 'contributions:category' 'healthmedicine' %}">Health & Medicine</a>
		</li>
		<li>
			<a href="{% url 'contributions:category' 'nonprofit' %}">NonProfits</a>
		</li>
		<li>
			<a href="{% url 'contributions:category' 'technology' %}">Technology</a>
		</li>
  	</ul>
</div>

core/templates/core/topNav_default.html
{% load url from future %}
<div class="top-nav">
	<div class="top-nav-inner">
		<a href="/"><img class="logo" src="https://d3fuw6vo22gqor.cloudfront.net/images/logos/le75.png" /></a>
	</div>
</div>

core/templates/core/topNav_detail_in.html
{% load url from future %}
<div class="top-nav">
	<div class="top-nav-inner">
		<a href="/"><img class="logo" src="https://d3fuw6vo22gqor.cloudfront.net/images/logos/le75.png" /></a>
		<div id="tab-group">
			<a href="#"class="tab toggle-nav-drop-down">
				<span>Explore ▾</span>
			</a>
			<div class="vertical-divider"></div>
			<a class="tab" href="{% url 'contributions:post' %}">
				<span>Contribute</span>
			</a>
			<div class="vertical-divider"></div>
			<a class="tab toggle-myaccount-drop-down">
				<span>My Account ▾</span>
			</a>
			<div class="vertical-divider"></div>
		</div>
		<div class="search">
			<form id="search_form" method="POST" action="{% url 'search:searchAll' %}">
				<input id="search" name="search" type="text" placeholder="Search Career Experiences" />
				{% csrf_token %}
			</form>
		</div>
	</div>
</div>
{% include "core/dropdowns.html" %}

core/templates/core/topNav_detail_out.html
{% load url from future %}
<div class="top-nav">
	<div class="top-nav-inner">
		<a href="/"><img class="logo" src="https://d3fuw6vo22gqor.cloudfront.net/images/logos/le75.png" /></a>
		<div id="tab-group">
			<a href="#"class="tab toggle-nav-drop-down">
				<span>Explore ▾</span>
			</a>
			<div class="vertical-divider"></div>
			<a class="tab" href="{% url 'contributions:post' %}">
				<span>Contribute</span>
			</a>
			<div class="vertical-divider"></div>
		</div>
		<div class="search">
			<form id="search_form" method="POST" action="{% url 'search:searchAll' %}">
				<input id="search" name="search" type="text" placeholder="Search Career Experiences" />
				{% csrf_token %}
			</form>
		</div>
	</div>
</div>
{% include "core/dropdowns.html" %}